name: 'CodeKeepers Review Request Action'
description: 'Automatically post your Pull Requests for review at the CodeKeepers Discord Server'
author: 'CodeKeepers'
inputs:
  api_token:
    description: 'API token for authenticating with the CodeKeepers endpoint'
    required: true
  pr_url:
    description: 'The pull request URL'
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Check PR description for #discord
      run: |
        if ! echo "${{ github.event.pull_request.body }}" | grep -q "#discord"; then
          echo "Pull request description does not contain #discord"
          exit 1
        fi
    - name: Check repository privacy
      run: |
        if [ "${{ github.event.repository.private }}" = "true" ]; then
          echo "Repository is private. Exiting."
          exit 1
        fi
    - name: Check README badge
      run: |
        if ! grep -q 'Join CodeKeepers' README.md; then
          echo "Badge not found in README.md. DM vulps on discord to ask for verification"
          exit 1
        fi
    - name: Verify badge commit author
      run: |
        line=$(grep -n 'Join CodeKeepers' README.md | cut -d: -f1 | head -n 1)
        blame=$(git blame -L ${line},${line} README.md)
        echo "$blame"
        if ! echo "$blame" | grep -q "Vulps22"; then
          echo "Badge was not committed by Vulps22. The badge must be committed by Vulps22 to be authentic"
          exit 1
        fi
    - name: Send review request
      run: |
        curl -X POST https://vulps.co.uk/codekeepers/api/review-request \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ inputs.api_token }}" \
          -d "{\"url\": \"${{ github.event.pull_request.html_url }}\", \"username\": \"${{ github.repository_owner }}\"}"
